2023-07-19 16:36:02,711 ERROR: Exception on / [GET] [in C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\routes.py", line 21, in index
    return render_template('index.html', title='Home page', form=form, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\index.html", line 19, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\_post.html", line 3, in top-level template code
    <td><img src="{{ user.avatar(36) }}"></td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-07-19 16:37:17,529 ERROR: Exception on /explore [GET] [in C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\routes.py", line 133, in explore
    return render_template('index.html', title='Explore', posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\index.html", line 19, in block 'content'
    {% include "_post.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\app\templates\_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\Documents\GitHub\Journal-Website\venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-07-20 17:38:14,598 INFO: Microblog startup [in C:\Users\yohan\Documents\GitHub\Journal-Website\app\__init__.py:45]
